resources:
    - name: repo
      type: git
      source:
        uri: ((git-repo))
    
    - name: test-image
      type: registry-image
      source:
        repository: ((docker-repo))
        username: ((docker-user))
        password: ((docker-password))
    
jobs:
    - name: build-and-push
      plan:
      # fetch repository source (containing Dockerfile)
      - get: repo
        trigger: true
      # build using `oci-build` task
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          params:
            DOCKERFILE: docker/Dockerfile
    
          inputs:
          - name: repo
            path: .
    
          outputs:
          - name: image
    
          run:
            path: build
      - task: scan
        config:
          platform: linux
          image_resource:
              type: registry-image
              source:
                  repository: aquasec/trivy
          inputs:
          - name: image
            path: .

          run: 
            path: trivy
            args: ["image", "--input", "image.tar"]

            
      # push using `registry-image` resource
      - put: test-image
        params: {image: image/image.tar}